### PR TITLE
[release-v1.11] Use HPA v2

### PR DESCRIPTION
**Pull request by pierDipi**
We can now use HPA v2 directly

For 1.32, our min OCP version is 4.11 and these 2 resources are documentation validation, v2 is served since 1.23 k8s and OCP 4.11 is k8s 1.24.

https://access.redhat.com/solutions/4870701
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

### CODE REVIEW

**Comment by pierDipi** [comment]
tracing gatherer data race
```
WARNING: DATA RACE
Write at 0x0000043698fa by goroutine 6563:
  knative.dev/reconciler-test/pkg/milestone.NewTracingGatherer()
      /go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/milestone/emitter_tracing.go:52 +0x12c
  knative.dev/reconciler-test/pkg/tracing.WithGatherer.func1()
      /go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/tracing/tracing.go:36 +0x113
  knative.dev/reconciler-test/pkg/environment.(*MagicGlobalEnvironment).Environment()
      /go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/environment/magic.go:203 +0x510
  knative.dev/eventing/test/rekt.TestChannelDeadLetterSinkExtensions()
      /go/src/github.com/openshift-knative/eventing/test/rekt/channel_test.go:311 +0x249
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47

Previous write at 0x0000043698fa by goroutine 39:
  knative.dev/reconciler-test/pkg/milestone.NewTracingGatherer()
      /go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/milestone/emitter_tracing.go:52 +0x12c
  knative.dev/reconciler-test/pkg/tracing.WithGatherer.func1()
      /go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/tracing/tracing.go:36 +0x113
  knative.dev/reconciler-test/pkg/environment.(*MagicGlobalEnvironment).Environment()
      /go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/environment/magic.go:203 +0x510
  knative.dev/eventing/test/rekt.TestBrokerWithManyTriggers()
      /go/src/github.com/openshift-knative/eventing/test/rekt/broker_test.go:41 +0x2b8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47

Goroutine 6563 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1726 +0xa84
  knative.dev/eventing/test/rekt.TestMain()
      /go/src/github.com/openshift-knative/eventing/test/rekt/main_test.go:46 +0xae
  main.main()
      _testmain.go:185 +0x324

Goroutine 39 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1726 +0xa84
  knative.dev/eventing/test/rekt.TestMain()
      /go/src/github.com/openshift-knative/eventing/test/rekt/main_test.go:46 +0xae
  main.main()
      _testmain.go:185 +0x324
```

**Comment by maschmid** [comment]
opening https://github.com/knative-extensions/reconciler-test/pull/655 for backporting the data race fix to reconciler-test release-1.11

**Comment by pierDipi** [comment]
Merging manually

**Comment by pierDipi** [comment]
We're getting 
```
[1/2] STEP 6/6: RUN go build -o /tmp/operator ${BASE}/openshift-knative-operator/cmd/operator
go: errors parsing go.mod:
/go/src/github.com/openshift-knative/serverless-operator/go.mod:5: unknown directive: toolchain
```

**Pull request merged**
