### PR TITLE
[release-v1.10] :bug: Backport proper Istio' quit

### PR DESCRIPTION
**Pull request by cardil**
Fixes https://issues.redhat.com/browse/SRVKE-1522
Related to https://github.com/knative-extensions/reconciler-test/pull/591

## Proposed Changes

- :bug: Backport proper Istio' quit

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
You need to re-run `make generate-release`

**Comment by cardil** [comment]
/test 410-test-e2e-aws-ocp-410

Infra failure

**Comment by cardil** [comment]
/test 410-test-e2e-aws-ocp-410

Infra failure

**Review by pierDipi — CHANGES_REQUESTED** [review]
There are unrelated changes to vendor

/hold

**Comment by cardil** [comment]
Yeah, I saw them.

But, how is that possible? There were manual changes done to this repo, or patches?

**Comment by pierDipi** [comment]
Yes, there are patches in `openshift/patches` for those changes

**Comment by cardil** [comment]
> Yes, there are patches in `openshift/patches` for those changes

Damn. We should have a linter to check this...

**Review by pierDipi — APPROVED** [review]
Thanks @cardil 

/lgtm
/approve

**Pull request merged**
