### PR TITLE
[release-v1.9] Send namespace header in MT components

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick of https://github.com/openshift-knative/eventing/commit/a4d26826f7975665edf0a041ff2b54c3275da6ef and https://github.com/openshift-knative/eventing/commit/f0d6382ed160366e30f3ce2f335ee67ef8df4c7b

Send namespace header in MT components needs the PingSource adapter client creation refactoring

### CODE REVIEW

**Comment by pierDipi** [comment]
```
invalid value "1.19" for flag -compat: maximum supported Go version is 1.18
usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
Run 'go help mod tidy' for details.
make[1]: *** [generated-files] Error 2
```

**Comment by pierDipi** [comment]
```
invalid value "1.19" for flag -compat: maximum supported Go version is 1.18
usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
Run 'go help mod tidy' for details.
make[1]: *** [generated-files] Error 2
```

I think we might need to bump to Go 1.19

**Comment by pierDipi** [comment]
Maybe it will be fixed by https://github.com/openshift-knative/eventing/pull/266

**Review by creydr — APPROVED** [review]
/lgtm

**Pull request merged**
