### PR TITLE
[release-v1.13] wathola receiver, annotate span by step number

### PR DESCRIPTION
**Pull request by maschmid**
backports https://github.com/knative/eventing/pull/7667

### CODE REVIEW

**Comment by creydr** [comment]
@maschmid we fixed a couple of issues in 1.13 (which lead to some CI failures). Can you rebase this PR?

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by matzew** [comment]
/retest

not sure why now all fail, after all was green ....

**Comment by creydr** [comment]
`"origin-operator-registry:4.15" is invalid: from: Error resolving ImageStreamTag origin-operator-registry:4.15 in namespace openshift-marketplace: unable to find latest tagged image`
/retest

**Pull request closed without merging**
