### PR TITLE
[release-v1.15] Add Konflux configurations

### PR DESCRIPTION
**Pull request by serverless-qe**
Add Konflux components and pipelines

### CODE REVIEW

**Comment by creydr** [comment]
Some Konflux runs are failing, as it seems we have some new components now, and the yaml are not applied for them yet

**Comment by pierDipi** [comment]
@creydr yes, we need to just merge this

**Comment by pierDipi** [comment]
The new components are test images

**Comment by creydr** [comment]
> yes, we need to just merge this

But after the next run, so we don't have the image refs updated (https://github.com/openshift-knative/hack/pull/215) I guess

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Merging this one

**Pull request merged**
