### PR TITLE
Remove 005-k8s-min.patch for patching minKubeVersion

### PR DESCRIPTION
**Pull request by mgencur**
The error was:
```
error: while searching for:
 	// NOTE: If you are changing this line, please also update the minimum kubernetes
 	// version listed here:
 	// https://github.com/knative/docs/blob/mkdocs/docs/snippets/prerequisites.md
 	defaultMinimumVersion = "v1.24.0"
)
 
 func getMinimumVersion() string {
 
 error: patch failed: vendor/knative.dev/pkg/version/version.go:33
```

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
Technically, we don't need this patch anymore since the operator is now injecting it as environment variable to every deployment, so we could us from keep maintaining this (costly) patch

**Comment by pierDipi** [comment]
Ref: https://github.com/openshift-knative/serverless-operator/pull/1816

**Comment by mgencur** [comment]
@pierDipi Should we just remove the patch?

**Comment by pierDipi** [comment]
Yes, I'd propose to do that instead

**Comment by mgencur** [comment]
> Ref: https://github.com/openshift-knative/serverless-operator/pull/1816

Hmm. But that's in s-o. We probably still need to patch for this Eventing repository?

**Comment by mgencur** [comment]
OK. Removed the patch.

**Review by pierDipi — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
