### PR TITLE
[release-v1.14] workaround DeepDerivative CreationTimestamp comparison

### PR DESCRIPTION
**Pull request by maschmid**
fixes https://issues.redhat.com/browse/SRVKE-1666

### CODE REVIEW

**Comment by maschmid** [comment]
/test 413-test-encryption-auth-e2e-aws-413

> Error from server (BadRequest): unable to wait for build serverless-openshift-knative-operator-2 to run: timed out waiting for the condition

**Comment by maschmid** [comment]
>   Warning  Failed          14m (x2 over 14m)  kubelet            Failed to pull image "registry.build09.ci.openshift.org/ci-op-wvmx2pkg/pipeline@sha256:eeca31b19c634a16da4a7adb116db218e7fc7799c08cb249d1951ca84ef7e433": copying system image from manifest list: parsing image configuration: fetching blob: received unexpected HTTP status: 500 Internal Server Error

/test 416-test-encryption-auth-e2e-aws-416

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
