### PR TITLE
Update reconciler-test to latest commit in release-1.11

### PR DESCRIPTION
**Pull request by creydr**
# Changes
- Update reconciler-test to latest commit in release-1.11
- Incorporates https://github.com/knative-extensions/reconciler-test/pull/578
- Incorporates https://github.com/knative-extensions/reconciler-test/pull/574
- Incorporates https://github.com/knative-extensions/reconciler-test/pull/560
- Incorporates https://github.com/knative-extensions/reconciler-test/pull/558

### CODE REVIEW

**Comment by creydr** [comment]
Follow up on https://github.com/openshift-knative/eventing/pull/309#issuecomment-1674531547

/assign @matzew

**Comment by ReToCode** [comment]
You might want to include the [latest one](https://github.com/knative-extensions/reconciler-test/commit/9e58415bcb8462ed315b1924580381d75a5c0f12) as well?

**Comment by creydr** [comment]
> You might want to include the [latest one](https://github.com/knative-extensions/reconciler-test/commit/9e58415bcb8462ed315b1924580381d75a5c0f12) as well?

Included the commits from https://github.com/knative-extensions/reconciler-test/commit/9e58415bcb8462ed315b1924580381d75a5c0f12 too

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
