### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by pierDipi** [comment]
```
Container test exited with code 4, reason Error
---
dns.aws_route53_record.api_external_internal_zone_alias[0]
level=error msg=2024-04-16T01:49:24.203Z [INFO]  Starting apply for module.dns.aws_route53_record.api_internal_alias[0]
level=error msg=2024-04-16T01:49:24.203Z [INFO]  Starting apply for module.vpc.aws_lb_listener.api_internal_api
level=error msg=2024-04-16T01:49:24.204Z [INFO]  Starting apply for module.vpc.aws_lb_listener.api_internal_services
level=error msg=2024-04-16T01:49:43.683Z [INFO]  Starting apply for module.dns.aws_route53_record.api_external_alias[0]
level=error
level=error msg=Error: creating EC2 EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
level=error msg=	status code: 400, request id: 82b383d0-9929-46b1-b3a7-87e7f4f1aba6
level=error
level=error msg=  with module.vpc.aws_eip.nat_eip[0],
level=error msg=  on vpc/vpc-public.tf line 68, in resource "aws_eip" "nat_eip":
level=error msg=  68: resource "aws_eip" "nat_eip" {
level=error
level=error
level=error msg=Error: creating EC2 EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
level=error msg=	status code: 400, request id: 72be9e98-4fee-4764-b42b-96ff60ca6ac4
level=error
level=error msg=  with module.vpc.aws_eip.nat_eip[1],
level=error msg=  on vpc/vpc-public.tf line 68, in resource "aws_eip" "nat_eip":
level=error msg=  68: resource "aws_eip" "nat_eip" {
level=error
level=error
```

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
