### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by creydr** [comment]
```
{Failed  === RUN   TestContainerSourceSendsEventsWithOIDC/SendsEventsWithSinkRefOIDC/Assert/containersource_as_event_source_uses_containersources_identity_for_OIDC
=== PAUSE TestContainerSourceSendsEventsWithOIDC/SendsEventsWithSinkRefOIDC/Assert/containersource_as_event_source_uses_containersources_identity_for_OIDC
=== CONT  TestContainerSourceSendsEventsWithOIDC/SendsEventsWithSinkRefOIDC/Assert/containersource_as_event_source_uses_containersources_identity_for_OIDC
    event_info_store.go:181: Assert in range failed: expected <= 1 events, saw 7
        knative.dev/reconciler-test/pkg/eventshub.(*Store).AssertInRange
        	/go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go:181
        knative.dev/reconciler-test/pkg/eventshub.(*Store).AssertExact
        	/go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go:205
        knative.dev/eventing/test/rekt/features/containersource.SendsEventsWithSinkRefOIDC.MatchAssertionBuilder.Exact.func10
        	/go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go:110
        knative.dev/reconciler-test/pkg/environment.(*MagicEnvironment).executeStep.func1
        	/go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/environment/execution.go:67
        testing.tRunner
        	/usr/lib/golang/src/testing/testing.go:1595
        runtime.goexit
        	/usr/lib/golang/src/runtime/asm_amd64.s:1650
--- FAIL: TestContainerSourceSendsEventsWithOIDC/SendsEventsWithSinkRefOIDC/Assert/containersource_as_event_source_uses_containersources_identity_for_OIDC (25.11s)
}
```

:thinking: 

Proposed https://github.com/knative/eventing/pull/7903

**Comment by creydr** [comment]
```
{Failed  === RUN   TestApiServerSourceNewFiltersFeature/Knative_ApiServerSource_-_Features_-_New_Filter/Filters_properly_the_messages/Setup/install_ApiServerSource
=== PAUSE TestApiServerSourceNewFiltersFeature/Knative_ApiServerSource_-_Features_-_New_Filter/Filters_properly_the_messages/Setup/install_ApiServerSource
=== CONT  TestApiServerSourceNewFiltersFeature/Knative_ApiServerSource_-_Features_-_New_Filter/Filters_properly_the_messages/Setup/install_ApiServerSource
    apiserversource.go:62: failed to create resource admission webhook "validation.webhook.eventing.knative.dev" denied the request: validation failed: Filters is not empty but the NewAPIServerFilters feature is disabled.:  - Resource:
        apiVersion: sources.knative.dev/v1
        kind: ApiServerSource
        metadata:
          name: apiserversource-djwxqblq
          namespace: test-npwodfzx
        spec:
          filters:
            - exact:
                type: dev.knative.apiserver.resource.update
          mode: Resource
          resources:
            - apiVersion: v1
              kind: Pod
          serviceAccountName: apiserversource-hslgaznx
          sink:
            ref:
              apiVersion: v1
              kind: Service
              name: sink-evkltput
              namespace: null
        
--- FAIL: TestApiServerSourceNewFiltersFeature/Knative_ApiServerSource_-_Features_-_New_Filter/Filters_properly_the_messages/Setup/install_ApiServerSource (6.09s)
}
```

Related to https://github.com/knative/eventing/pull/7799/files, as we don't have the `new-apiserversource-filters` enabled and they run as part of the main suite. So either enable the FF in our tests too, or wait for https://github.com/knative/eventing/pull/7914/files, which moves the test to the experimental suite

**Comment by creydr** [comment]
```
Error from server (InternalError): error when creating "./hack/lib/certmanager_resources/selfsigned-issuer.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "[https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s](https://cert-manager-webhook.cert-manager.svc/mutate?timeout=10s)": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
/test 415-test-conformance-aws-415

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
