### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by creydr** [comment]
48 reconciler test seems to fail due to some
```
"User system:serviceaccount:test-vgrbnynh:apiserversource-jeyhbzrf cannot get, list, watch resource \"pods\" in API group \"\" in Namespace \"test-vgrbnynh\""
```
(same for events)

:eyes: 

@pierDipi @aliok @matzew are you aware of any recent RBAC changes for the apiserversource?

**Comment by creydr** [comment]
in 48-test-reconciler-aws-ocp-48 is see an ApiServerSource not becoming ready because of `The Deployment 'apiserversource-apiserversourcebedf0f900c506331f8659412fd120a6a' is unavailable.`. Checking on the deployment, I see 
```
    - lastTransitionTime: "2023-03-09T01:56:59Z"
      lastUpdateTime: "2023-03-09T01:56:59Z"
      message: 'pods "apiserversource-apiserversourcebedf0f900c506331f8659412fd1wtdn8"
        is forbidden: unable to validate against any security context constraint:
        [pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/receive-adapter:
        Forbidden: seccomp may not be set provider "anyuid": Forbidden: not usable
        by user or serviceaccount provider "nonroot": Forbidden: not usable by user
        or serviceaccount provider "hostmount-anyuid": Forbidden: not usable by user
        or serviceaccount provider "machine-api-termination-handler": Forbidden: not
        usable by user or serviceaccount provider "hostnetwork": Forbidden: not usable
        by user or serviceaccount provider "hostaccess": Forbidden: not usable by
        user or serviceaccount provider "node-exporter": Forbidden: not usable by
        user or serviceaccount provider "privileged": Forbidden: not usable by user
        or serviceaccount]'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
```
@matzew does this ring any bells regarding your seccomp change (https://github.com/knative/eventing/commit/397387e592d8ab89e475fbd1d56c64a81f8259d2)?

**Comment by pierDipi** [comment]
Ah yes, RuntimeDefault should be dropped in openshift and let it default for us

**Comment by creydr** [comment]
> Ah yes, RuntimeDefault should be dropped in openshift and let it default for us

Updated the patch: https://github.com/openshift-knative/eventing/pull/152

**Pull request merged**
