### PR TITLE
Enable delivery timeout feature

### PR DESCRIPTION
**Pull request by pierDipi**
This is needed by EKB, as discussed on Slack

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold
Should we open a JIRA and say that this is enabled,... being Tech Preview (TP)?  I know we need for the broker

**Comment by pierDipi** [comment]
> /lgtm /approve
> 
> /hold Should we open a JIRA and say that this is enabled,... being Tech Preview (TP)? I know we need for the broker

https://issues.redhat.com/browse/SRVKE-1351

**Pull request merged**
