### PR TITLE
[release-v1.15] Install tzdata

### PR DESCRIPTION
**Pull request by creydr**

### CODE REVIEW

**Comment by pierDipi** [comment]
It's failing :thinking:

**Comment by pierDipi** [comment]
```
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN microdnf update tzdata -y && microdnf reinstall tzdata -y": exit status 1
```

**Comment by creydr** [comment]
```
Couldn't retrieve Task "resolver type bundles\nname = prefetch-dependencies-oci-ta\n": error requesting remote resource: resolution took longer than global timeout of 1m0s
```
/retest

**Comment by creydr** [comment]
```
Pipeline ocp-serverless-tenant/kn-eventing-heartbeats-receiver-115-on-pull-request-jb842 can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "resolver type bundles\nname = init\n": error requesting remote resource: resolution took longer than global timeout of 1m0s
```
/retest

**Comment by pierDipi** [comment]
`Red Hat Konflux / kn-eventing-mtping-115-on-pull-request` passed

**Comment by pierDipi** [comment]
> /cherry-pick release-v1.16

already done

**Pull request merged**
