### PR TITLE
[main] Add TLS updates to main

### PR DESCRIPTION
**Pull request by pierDipi**
As per title

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
Needs rebase

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by creydr** [comment]
4faf54da81c937cb02b2aecc8b30af4f140e0723 should then also fix some CI issues (https://github.com/openshift-knative/eventing/pull/490#issuecomment-1916290007) :+1:

**Pull request merged**
