### PR TITLE
[release-v1.11] Fix view role aggregation

### PR DESCRIPTION
**Pull request by creydr**
Backport of #295

/assign @matzew @pierDipi

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
> @pierDipi: cannot checkout `release-1.v10`: error checking out release-1.v10: exit status 1. output: error: pathspec 'release-1.v10' did not match any file(s) known to git

I'll push a branch...

**Pull request merged**
