### PR TITLE
[release-v1.11] :bug: Backport proper Istio' quit

### PR DESCRIPTION
**Pull request by cardil**
Fixes https://issues.redhat.com/browse/SRVKE-1522
Related to https://github.com/knative-extensions/reconciler-test/pull/591

## Proposed Changes

- :bug: Backport proper Istio' quit

### CODE REVIEW

**Comment by cardil** [comment]
/test 411-test-e2e-aws-ocp-411

Looks like an infra failure

**Comment by cardil** [comment]
/test 411-test-conformance-aws-ocp-411

Also, looks like a infra failure

**Comment by cardil** [comment]
/test 413-test-conformance-aws-ocp-413

Same error as the others - looks like an infra

**Comment by cardil** [comment]
/hold

Patched files are overriten

**Comment by cardil** [comment]
I reapplied the patches. Now it matches the changes from: https://github.com/knative-extensions/reconciler-test/compare/9e58415bcb84...f561fc2e2d66

**Comment by cardil** [comment]
/test 413-test-reconciler-aws-ocp-413

I think this might be an infra failure

**Comment by maschmid** [comment]
Do we still need to hold this?

**Review by pierDipi — APPROVED** [review]
No!

/lgtm
/approve

**Comment by pierDipi** [comment]
Thanks @cardil

**Pull request merged**
