### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by pierDipi** [comment]
I'm looking into the failures

**Comment by creydr** [comment]
```
"Referenced \"ClusterIssuer\" not found: clusterissuer.cert-manager.io \"knative-eventing-ca-issuer\" not found"
```
seems we're not creating the knative-eventing-ca-issuer

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
