### PR TITLE
[release-v1.15] Run `make generate-release`

### PR DESCRIPTION
**Pull request by serverless-qe**
Run `make generate-release` using openshift-knative/hack.

### CODE REVIEW

**Comment by mgencur** [comment]
This adds the production-ready images as recently implemented in openshift-knative/hack

**Comment by pierDipi** [comment]
```
Task Statuses:
Failed to create PVC for PipelineRun ocp-serverless-tenant/knative-eventing-webhook-release-v115-on-pull-request-zlzkj correctly: PVC creation error: failed to create PVC pvc-a74ca122a7: persistentvolumeclaims "pvc-a74ca122a7" is forbidden: exceeded quota: storage, requested: count/persistentvolumeclaims=1, used: count/persistentvolumeclaims=180, limited: count/persistentvolumeclaims=180
```
This is a little annoying

**Pull request merged**
