### PR TITLE
Run rekt tests with `new-apiserversource-filters` feature flag enabled

### PR DESCRIPTION
**Pull request by creydr**

### CODE REVIEW

**Comment by creydr** [comment]
As discussed
/cc @matzew @pierDipi

**Review by pierDipi — COMMENTED** [review]
Have you considered enabling it here directly https://github.com/openshift-knative/serverless-operator/blob/main/test/v1beta1/resources/operator.knative.dev_v1beta1_knativeeventing_cr.yaml?
so that we don't need to worry about this when times for bumping to 1.15 comes? I think it's safe for this feature to be enabled during testing

**Comment by creydr** [comment]
> Have you considered enabling it here directly https://github.com/openshift-knative/serverless-operator/blob/main/test/v1beta1/resources/operator.knative.dev_v1beta1_knativeeventing_cr.yaml? so that we don't need to worry about this when times for bumping to 1.15 comes? I think it's safe for this feature to be enabled during testing

I can enable it in SO also directly. Only for clarification: what do you mean with the issues at the 1.15 bump?

**Comment by pierDipi** [comment]
I mean that when we bump to 1.15 we would need to that in that file?

**Comment by creydr** [comment]
Closing in favor for https://github.com/openshift-knative/serverless-operator/pull/2660

**Pull request closed without merging**
