### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by creydr** [comment]
No Golang 1.22 image available:
```
Trying to pull registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.22-openshift-4.16...
Warning: Pull failed, retrying in 5s ...
```

**Comment by pierDipi** [comment]
```
INFO[2024-07-31T09:20:39Z] openshift/e2e-rekt-tests.sh
make: execvp: openshift/e2e-rekt-tests.sh: Permission denied
```

**Comment by pierDipi** [comment]
Somehow the must-gather is empty :(

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-knative_eventing/623/pull-ci-openshift-knative-eventing-release-next-415-test-encryption-auth-e2e-aws-415/1821846595344273408/artifacts/

/retest

**Comment by pierDipi** [comment]
hmm

```
ERRO[2024-08-09T14:00:15Z] Some steps failed:                           
ERRO[[20](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-knative_eventing/623/pull-ci-openshift-knative-eventing-release-next-415-test-encryption-auth-e2e-aws-415/1821909222728667136#1:build-log.txt%3A20)24-08-09T14:00:15Z] 
  * could not initialize namespace: failed to wait for authentication cache to warm up after 15s: projects.project.openshift.io "ci-op-792xdwb0" is forbidden: User "system:serviceaccount:ci:ci-operator" cannot get resource "projects" in API group "project.openshift.io" in the namespace "ci-op-792xdwb0" 
INFO[2024-08-09T14:00:15Z] Reporting job state 'failed' with reason 'initializing_namespace'

```
/retest-required

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
