### PR TITLE
SRVKE-1523: [release-v1.11] Re-add removed HPA for ingress and filter

### PR DESCRIPTION
**Pull request by pierDipi**
Similar to https://github.com/openshift-knative/eventing/pull/364 for 1.11

### CODE REVIEW

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by nak3** [comment]
@pierDipi @creydr 
HPA for `eventing-webhook`  has v2beta2 a patch https://github.com/openshift-knative/eventing/blob/release-v1.10/openshift/patches/keep_hpa_v2beta2_until_ocp_4.13.patch but you will not add it for these HPA?

I believe that it is no problem whether we have patch or not (actually the `keep_hpa_v2beta2_until_ocp_4.13.patch` is unnecessary) but I think we should avoid this kind of inconsistency.

**Comment by pierDipi** [comment]
Thanks for the input @nak3, I'll remove the patch in a follow up PR

**Pull request merged**
