### PR TITLE
[RELEASE-1.6] Use v1beta1 for Knative operator crd in tests

### PR DESCRIPTION
**Pull request by skonto**
- See failure https://github.com/openshift-knative/serverless-operator/pull/1818#issuecomment-1321879979

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
There is a patch to update as well: https://github.com/openshift-knative/eventing/blob/main/openshift/patches/018-e2e-test-so-fix-TestBrokerNamespaceDefaulting.patch

**Comment by skonto** [comment]
here: https://github.com/openshift-knative/eventing/pull/12 @pierDipi could you stamp this one to unblock the S-O side?

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
