### PR TITLE
[release-v1.15] Add Istio inject label (#8205)

### PR DESCRIPTION
**Pull request by matzew**
backport of 8205 to ours

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
@matzew please rerun `make generate-release`

**Comment by matzew** [comment]
@pierDipi running `make generate-release` on my branch seems to ignore these patches:
https://github.com/openshift-knative/eventing/blob/release-v1.15/openshift/release/generate-release.sh#L15-L16

it gets reverted. :man_shrugging:

**Comment by pierDipi** [comment]
I'll merge and get the bot to do it

**Comment by pierDipi** [comment]
https://github.com/openshift-knative/hack/actions/runs/11229974345

**Comment by pierDipi** [comment]
https://github.com/openshift-knative/eventing/pull/894

**Pull request merged**
