### PR TITLE
Update reconciler-test to latest commit in release-1.10

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Update reconciler-test to latest commit in release-1.10
- Incorporates https://github.com/knative-extensions/reconciler-test/pull/573

### CODE REVIEW

**Review by creydr — COMMENTED** [review]
/lgtm

**Comment by matzew** [comment]
@ReToCode or @creydr  we need this on the 1.11 midstream branch, as well.
Would one of you mind doing that?

**Comment by creydr** [comment]
> @ReToCode or @creydr we need this on the 1.11 midstream branch, as well. Would one of you mind doing that?

I can take care of this on Monday

**Pull request merged**
