### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by creydr** [comment]
```
pinging container registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp: lookup image-registry.openshift-image-registry.svc on 172.30.0.10:53: no such host
```
/retest

**Comment by creydr** [comment]
We probably need https://github.com/knative/eventing/pull/7934/files (at least for `test-e2e-aws`)

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
